# Generated by Django 5.1.6 on 2025-02-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': '文章信息'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
